#MAIN VARIABLES
# Declares necessary variables
    declare -a -g STATE_MACHINE_BOLD=( );
    declare -a -g STATE_MACHINE_ITALIC=( );
    declare -a -g STATE_MACHINE_UNDERLINE=( );
    declare -a -g STATE_MACHINE_COLOR=( );
    declare -a -g STATE_MACHINE_BACKGROUND=( );
    declare -a -g STATE_MACHINE_INDENT=( );
#    declare STATE_MACHINE_LIST=0;
#BOLD,ITALIC,UNDERLINE
    PRE_BOLD="1";
    PRE_ITALIC="3";
    PRE_UNDERLINE="4";
#COLORS:
    PRE_COLOR_REVERSED="7";
    PRE_COLOR_RED="91";
    PRE_COLOR_GRAY="90";
    PRE_COLOR_YELLOW="93";
    PRE_COLOR_GREEN="32";
    PRE_COLOR_BLUE="34";
    PRE_COLOR_PURPLE="35";
    PRE_COLOR_WHITE="97"
    PRE_COLOR_BLACK="30"
#BACKGROUND:
    PRE_BACKGROUND_RED="101";
    PRE_BACKGROUND_GRAY="100";
    PRE_BACKGROUND_YELLOW="103";
    PRE_BACKGROUND_GREEN="42";
    PRE_BACKGROUND_BLUE="44";
    PRE_BACKGROUND_PURPLE="45";
    PRE_BACKGROUND_WHITE="107";
    PRE_BACKGROUND_DEFAULT="49";
#INDENTION:
    PRE_INDENT_1="\t";
    PRE_INDENT_2="\t\t";
    PRE_INDENT_3="\t\t\t";
    PRE_INDENT_4="\t\t\t\t";